--- 
- hosts: all  
  become: yes
  tasks:
  - name: install apache2 on node
    apt: 
      name: "{{mywebserverpack}}"
      state: present
    when: ansible_os_family=="Debian"

  - name: start apache2 on nodes
    service:
      name: "{{mywebserverpack}}"
      state: started
    when: ansible_os_family=="Debian"

  - name: install wget on nodes
    apt:
      name: wget
      state: present
    when: ansible_os_family=="Debian"

  - name: install git on nodes
    apt:
     name: git
     state: present
    when: ansible_os_family=="Debian"

  - name: install tree on nodes
    apt:
     name: tree 
     state: present 
