--- 
- hosts: 172.31.16.189 
  become: yes
  tasks: 
  - include_tasks: myfile.yml

  - name: create folder
    file:
      path: /home/admin/myfolder
      state: directory

  - name: copy a file into my directory
    copy:
      src: staticfile
      dest: /home/admin/myfolder/staticfile 

  - name: we need of to download files from internet 
    get_url:
      url: https://github.com/pradeepd282/Ansible-lab/blob/main/myfirstplaybook.yml
      dest: /home/admin/myfolder/myfirstplaybook.yml
      force_basic_auth: yes

  - name: install apache2 on nod
    apt:
     name: apache2
     state: present 

  - name: I want to change index page 
    template:
     src: myindex.j2
     dest: /var/www/html/index.html
    notify: restart webserver 

  - name: create folder
    file:
     path: /home/admin/myfolder1
     state: directory 

  - name: copy file on myfolder1
    copy:
     src: staticfiles
     dest: /home/admin/myfolder1/staticfiles

  handlers:
  - name: restart webserver
    service:
     name: apache2 
     state: restarted

  