--- 
- hosts: mydbservers 
  become: yes
  tasks:
  - name: install apache2 on node
    apt: 
      name: "{{mydbserverpack}}" 
      state: present
    when: ansible_os_family=="Debian"

  - name: start apache2 on nodes
    service:
      name: "{{mydbserverpack}}" 
      state: started
    when: ansible_os_family=="Debian"

  - name: install wget on nodes
    apt:
      name: "{{mydbserverwget}}"
      state: present
    when: ansible_os_family=="Debian"

  - name: install git on nodes
    apt:
     name: "{{mydbserverpackage}}"
     state: present
    when: ansible_os_family=="Debian"

  - name: install tree on nodes
    apt:
     name: "{{mydbserverpacking}}"
     state: present 

  - name: install ansible on nodes
    apt:
     name: "{{mydbserverpakage}}"
     state: present